services:
  journey-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: docker
      PROFILE: ""
      RUN_ID: "docker"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS:-false}"
    env_file:
      - ./docker/config/aws.env
      - ./docker/config/identity-service-helper.env
      - ./docker/config/identity-service-handler.env
      - .env.docker
    depends_on: []
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
      - ./playwright-report:/app/playwright-report
    networks:
      - identity-services

networks:
  identity-services:
    external: true