name: Daily Journey Tests (main)

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  run-main-tests:
    uses: ./.github/workflows/journey-tests.yml
    with:
      branch-set: main
      test: ''
      tag: ''
    secrets: inherit